name: Blue-Green Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      # 1. Клонируем репозиторий
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Настройка SSH вручную
      - name: Настройка SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SECRET_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H ${{ secrets.SECRET_HOST }} >> ~/.ssh/known_hosts

      # 3. Получаем текущее значение current_version.txt
      - name: Получаем текущее значение current_version.txt
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SECRET_HOST }}
          username: ${{ secrets.SECRET_USER }}
          key: ${{ secrets.SECRET_PRIVATE_KEY }}
          script: |
            cat /var/www/current_version.txt
          capture_stdout: true
        id: get-current-version

      # 4. Присваиваем значение в переменную окружения
            # 4. Присваиваем значение в переменную окружения
      - name: Присваиваем CURRENT_VERSION
        run: |
          CURRENT_VERSION=$(echo "${{ steps.get-current-version.outputs.stdout }}" | grep -Eo '(Test_blue|Test_green)')
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV

      # 5. Определяем TARGET_VERSION
      - name: Определяем TARGET_VERSION
        run: |
          if [[ "$CURRENT_VERSION" == "Test_blue" ]]; then
            echo "TARGET_VERSION=Test_green" >> $GITHUB_ENV
          else
            echo "TARGET_VERSION=Test_blue" >> $GITHUB_ENV
          fi

      # 6. Pull кода в нужную папку
      - name: Обновляем код на сервере
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SECRET_HOST }}
          username: ${{ secrets.SECRET_USER }}
          key: ${{ secrets.SECRET_PRIVATE_KEY }}
          script: |
            cd /var/www/$TARGET_VERSION
            git pull origin main

      # 7. Обновляем симлинк
      - name: Обновляем симлинк
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SECRET_HOST }}
          username: ${{ secrets.SECRET_USER }}
          key: ${{ secrets.SECRET_PRIVATE_KEY }}
          script: |
            echo "$TARGET_VERSION" | sudo tee /var/www/current_version.txt
            sudo /var/www/update_symlink.sh

      # 8. Проверяем результат
      - name: Проверяем результат
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SECRET_HOST }}
          username: ${{ secrets.SECRET_USER }}
          key: ${{ secrets.SECRET_PRIVATE_KEY }}
          script: |
            echo "Проверяем симлинк:"
            ls -l /var/www/current
            readlink -f /var/www/current
            echo "Текущая версия:"
            cat /var/www/current_version.txt
