name: Blue-Green Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Настройка SSH вручную
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SECRET_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H ${{ secrets.SECRET_HOST }} >> ~/.ssh/known_hosts

      - name: Получаем текущую версию (current_version)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SECRET_HOST }}
          username: ${{ secrets.SECRET_USER }}
          key: ${{ secrets.SECRET_PRIVATE_KEY }}
          script: |
            if [ -f /var/www/current_version.txt ]; then
              cat /var/www/current_version.txt
            else
              echo "Test_blue" > /var/www/current_version.txt
              cat /var/www/current_version.txt
            fi

      - name: Скачиваем current_version.txt
        run: |
          scp -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key ${{ secrets.SECRET_USER }}@${{ secrets.SECRET_HOST }}:/var/www/current_version.txt .

      - name: Определяем target_version
        run: |
          CURRENT_VERSION=$(cat current_version.txt)
          echo "Текущая версия: $CURRENT_VERSION"
          if [ "$CURRENT_VERSION" == "Test_blue" ]; then
            TARGET_VERSION="Test_green"
          else
            TARGET_VERSION="Test_blue"
          fi
          echo "TARGET_VERSION=${TARGET_VERSION}" >> $GITHUB_ENV
          echo "Следующая версия: $TARGET_VERSION"

      - name: Копируем index.html на сервер
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SECRET_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.SECRET_HOST }}
          REMOTE_USER: ${{ secrets.SECRET_USER }}
        with:
          source: ./index.html
          target: /var/www/${{ env.TARGET_VERSION }}

      - name: Обновляем симлинк и current_version.txt
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SECRET_HOST }}
          username: ${{ secrets.SECRET_USER }}
          key: ${{ secrets.SECRET_PRIVATE_KEY }}
          script: |
            echo "Обновляем симлинк на ${TARGET_VERSION}"
            sudo ln -sfn "/var/www/${TARGET_VERSION}" /var/www/current
            echo "${TARGET_VERSION}" | sudo tee /var/www/current_version.txt
            echo "Записали в current_version.txt:"
            cat /var/www/current_version.txt
            echo "Проверяем симлинк:"
            ls -l /var/www/current
            readlink -f /var/www/current
            sudo systemctl restart nginx
