name: Blue-Green Deploy Nginx

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Test SSH Connection
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SECRET_HOST }}
        username: ${{ secrets.SECRET_USER }}
        key: ${{ secrets.SECRET_PRIVATE_KEY }}
        port: 22
        script: |
          echo "Проверка соединения с сервером..."
          hostname
          whoami
          echo "Соединение успешно установлено!"

    - name: Determine Target Version
      id: set_version
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SECRET_HOST }}
        username: ${{ secrets.SECRET_USER }}
        key: ${{ secrets.SECRET_PRIVATE_KEY }}
        port: 22
        script: |
          CURRENT_VERSION=$(readlink /var/www/current || echo "none")
          if [[ "$CURRENT_VERSION" == "/var/www/Test_blue" ]]; then
            TARGET_VERSION="Test_green"
          else
            TARGET_VERSION="Test_blue"
          fi
          echo "TARGET_VERSION=${TARGET_VERSION}" >> $GITHUB_ENV

    - name: Copy files to target version
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SECRET_PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.SECRET_HOST }}
        REMOTE_USER: ${{ secrets.SECRET_USER }}
      with:
        source: ./index.html
        target: /var/www/${{ env.TARGET_VERSION }}/

    - name: Switch Nginx to New Version
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SECRET_HOST }}
        username: ${{ secrets.SECRET_USER }}
        key: ${{ secrets.SECRET_PRIVATE_KEY }}
        port: 22
        script: |
          echo "Переключение Nginx на ${TARGET_VERSION}..."
          sudo ln -sfn /var/www/${TARGET_VERSION} /var/www/current
          sudo systemctl reload nginx
