name: Blue-Green Deploy Nginx

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Test SSH Connection
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SECRET_HOST }}
        username: ${{ secrets.SECRET_USER }}
        key: ${{ secrets.SECRET_PRIVATE_KEY }}
        port: 22
        script: |
          echo "Проверка соединения с сервером..."
          hostname
          whoami
          echo "Соединение успешно установлено!"

    - name: Determine Target Version
      id: version_check
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SECRET_HOST }}
        username: ${{ secrets.SECRET_USER }}
        key: ${{ secrets.SECRET_PRIVATE_KEY }}
        port: 22
        script: |
          if [ "$(readlink /var/www/current)" = "/var/www/Test_blue" ]; then
            echo "green"
          else
            echo "blue"
          fi
      register-output: target_version

    - name: Set Target Version
      run: echo "target_version=${{ steps.version_check.outputs.target_version }}" >> $GITHUB_ENV

    - name: Copy files to target version
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SECRET_PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.SECRET_HOST }}
        REMOTE_USER: ${{ secrets.SECRET_USER }}
      with:
        source: ./index.html
        target: /var/www/Test_${{ env.target_version }}/

    - name: Switch Nginx to New Version
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SECRET_HOST }}
        username: ${{ secrets.SECRET_USER }}
        key: ${{ secrets.SECRET_PRIVATE_KEY }}
        port: 22
        script: |
          echo "Переключение Nginx на Test_${{ env.target_version }}..."
          sudo ln -sfn /var/www/Test_${{ env.target_version }} /var/www/current
          sudo systemctl reload nginx
