name: Blue-Green Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: install ssh keys
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SECRET_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H ${{ secrets.SECRET_HOST }} >> ~/.ssh/known_hosts

      - name: Code deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SECRET_HOST }}
          username: ${{ secrets.SECRET_USER }}
          key: ${{ secrets.SECRET_PRIVATE_KEY }}
          script: |
            echo "start code deploying..."
            sudo /var/www/deploy.sh

      - name: Symlink update
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SECRET_HOST }}
          username: ${{ secrets.SECRET_USER }}
          key: ${{ secrets.SECRET_PRIVATE_KEY }}
          script: |
            echo "start symlink update..."
            sudo /var/www/update_symlink.sh

      - name: Check result
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SECRET_HOST }}
          username: ${{ secrets.SECRET_USER }}
          key: ${{ secrets.SECRET_PRIVATE_KEY }}
          script: |
            echo "symlink check:"
            ls -l /var/www/current
            readlink -f /var/www/current
            echo "current version:"
            cat /var/www/current_version.txt
