name: Blue-Green Deploy Nginx

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Determine Active Version
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SECRET_HOST }}
        username: ${{ secrets.SECRET_USER }}
        key: ${{ secrets.SECRET_PRIVATE_KEY }}
        script: |
          if [ "$(readlink /var/www/current)" = "/var/www/Test_blue" ]; then
            echo "green" > ~/target_version.txt
          else
            echo "blue" > ~/target_version.txt
          fi

    - name: Get Target Version
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SECRET_HOST }}
        username: ${{ secrets.SECRET_USER }}
        key: ${{ secrets.SECRET_PRIVATE_KEY }}
        script: cat ~/target_version.txt
      id: target_version

    - name: Copy files to target version
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SECRET_PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.SECRET_HOST }}
        REMOTE_USER: ${{ secrets.SECRET_USER }}
        TARGET: /var/www/Test_${{ steps.target_version.outputs.stdout }}/
      with:
        source: ./index.html

    - name: Switch Nginx to New Version
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SECRET_HOST }}
        username: ${{ secrets.SECRET_USER }}
        key: ${{ secrets.SECRET_PRIVATE_KEY }}
        script: |
          sudo ln -sfn /var/www/Test_${{ steps.target_version.outputs.stdout }} /var/www/current
          sudo systemctl reload nginx
