name: Blue-Green Deploy Nginx

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Test SSH Connection
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SECRET_HOST }}
        username: ${{ secrets.SECRET_USER }}
        key: ${{ secrets.SECRET_PRIVATE_KEY }}
        port: 22
        script: |
          echo "Проверка соединения с сервером..."
          hostname
          whoami
          echo "Соединение успешно установлено!"

    - name: Add SSH Key
      run: |
        echo "${{ secrets.SECRET_PRIVATE_KEY }}" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        ssh-keyscan -H ${{ secrets.SECRET_HOST }} >> ~/.ssh/known_hosts

    - name: Determine Active Version
      id: version_check
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SECRET_HOST }}
        username: ${{ secrets.SECRET_USER }}
        key: ${{ secrets.SECRET_PRIVATE_KEY }}
        port: 22
        script: |
          if [ "$(readlink /var/www/current)" = "/var/www/Test_blue" ]; then
            echo "green" > ~/target_version.txt
          else
            echo "blue" > ~/target_version.txt
          fi
          cat ~/target_version.txt

    - name: Get Target Version
      id: get_target
      run: |
        echo "Получаем target_version..."
        target_version=$(ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no ${{ secrets.SECRET_USER }}@${{ secrets.SECRET_HOST }} 'cat ~/target_version.txt')
        echo "target_version=$target_version" >> $GITHUB_ENV
        echo "Target version: $target_version"

    - name: Copy files to target version
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SECRET_PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.SECRET_HOST }}
        REMOTE_USER: ${{ secrets.SECRET_USER }}
      with:
        source: ./index.html
        target: /var/www/Test_${{ env.target_version }}/

    - name: Switch Nginx to New Version
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SECRET_HOST }}
        username: ${{ secrets.SECRET_USER }}
        key: ${{ secrets.SECRET_PRIVATE_KEY }}
        port: 22
        script: |
          echo "Переключение Nginx на Test_${{ env.target_version }}..."
          sudo ln -sfn /var/www/Test_${{ env.target_version }} /var/www/current
          sudo systemctl reload nginx
